// Common IANA timezone identifiers grouped by region
export const TIMEZONE_OPTIONS = [
  { value: "Etc/UTC", label: "UTC" },
  // Americas
  { value: "America/New_York", label: "Eastern Time (New York)" },
  { value: "America/Chicago", label: "Central Time (Chicago)" },
  { value: "America/Denver", label: "Mountain Time (Denver)" },
  { value: "America/Los_Angeles", label: "Pacific Time (Los Angeles)" },
  { value: "America/Anchorage", label: "Alaska Time" },
  { value: "America/Phoenix", label: "Arizona (No DST)" },
  { value: "America/Toronto", label: "Eastern Time (Toronto)" },
  { value: "America/Vancouver", label: "Pacific Time (Vancouver)" },
  { value: "America/Sao_Paulo", label: "Brasilia Time" },
  { value: "America/Mexico_City", label: "Central Time (Mexico City)" },
  { value: "America/Buenos_Aires", label: "Argentina Time" },
  { value: "America/Santiago", label: "Chile Time" },
  // Europe
  { value: "Europe/London", label: "London (GMT/BST)" },
  { value: "Europe/Paris", label: "Central European Time (Paris)" },
  { value: "Europe/Berlin", label: "Central European Time (Berlin)" },
  { value: "Europe/Madrid", label: "Central European Time (Madrid)" },
  { value: "Europe/Rome", label: "Central European Time (Rome)" },
  { value: "Europe/Amsterdam", label: "Central European Time (Amsterdam)" },
  { value: "Europe/Stockholm", label: "Central European Time (Stockholm)" },
  { value: "Europe/Oslo", label: "Central European Time (Oslo)" },
  { value: "Europe/Copenhagen", label: "Central European Time (Copenhagen)" },
  { value: "Europe/Brussels", label: "Central European Time (Brussels)" },
  { value: "Europe/Vienna", label: "Central European Time (Vienna)" },
  { value: "Europe/Zurich", label: "Central European Time (Zurich)" },
  { value: "Europe/Warsaw", label: "Central European Time (Warsaw)" },
  { value: "Europe/Moscow", label: "Moscow Time" },
  { value: "Europe/Athens", label: "Eastern European Time (Athens)" },
  { value: "Europe/Helsinki", label: "Eastern European Time (Helsinki)" },
  { value: "Europe/Istanbul", label: "Turkey Time (Istanbul)" },
  // Asia & Pacific
  { value: "Asia/Tokyo", label: "Japan Standard Time (Tokyo)" },
  { value: "Asia/Shanghai", label: "China Standard Time (Shanghai)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong Time" },
  { value: "Asia/Singapore", label: "Singapore Time" },
  { value: "Asia/Seoul", label: "Korea Standard Time (Seoul)" },
  { value: "Asia/Dubai", label: "Gulf Standard Time (Dubai)" },
  { value: "Asia/Kolkata", label: "India Standard Time (Kolkata)" },
  { value: "Asia/Bangkok", label: "Indochina Time (Bangkok)" },
  { value: "Asia/Jakarta", label: "Western Indonesia Time (Jakarta)" },
  { value: "Asia/Manila", label: "Philippine Time (Manila)" },
  { value: "Asia/Taipei", label: "Taiwan Time (Taipei)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia Time (Kuala Lumpur)" },
  { value: "Asia/Ho_Chi_Minh", label: "Indochina Time (Ho Chi Minh)" },
  { value: "Asia/Jerusalem", label: "Israel Time (Jerusalem)" },
  { value: "Asia/Riyadh", label: "Arabia Standard Time (Riyadh)" },
  // Australia & Oceania
  { value: "Australia/Sydney", label: "Australian Eastern Time (Sydney)" },
  {
    value: "Australia/Melbourne",
    label: "Australian Eastern Time (Melbourne)",
  },
  {
    value: "Australia/Brisbane",
    label: "Australian Eastern Time (Brisbane, No DST)",
  },
  { value: "Australia/Perth", label: "Australian Western Time (Perth)" },
  { value: "Australia/Adelaide", label: "Australian Central Time (Adelaide)" },
  { value: "Pacific/Auckland", label: "New Zealand Time (Auckland)" },
  { value: "Pacific/Fiji", label: "Fiji Time" },
  { value: "Pacific/Honolulu", label: "Hawaii-Aleutian Time" },
  // Africa
  { value: "Africa/Johannesburg", label: "South Africa Standard Time" },
  { value: "Africa/Cairo", label: "Eastern European Time (Cairo)" },
  { value: "Africa/Lagos", label: "West Africa Time (Lagos)" },
  { value: "Africa/Nairobi", label: "East Africa Time (Nairobi)" },
  { value: "Africa/Casablanca", label: "Western European Time (Casablanca)" },
] as const;

export type TimezoneValue = (typeof TIMEZONE_OPTIONS)[number]["value"];
